name: Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Setup private repo access
      uses: extractions/netrc@v1
      with:
        machine: github.com
        username: JOHNEPPILLAR
        password: ${{ secrets.REPO_ACCESS }}

    - name: Set private repo
      run: go env -w GOPRIVATE=github.com/JOHNEPPILLAR

    - name: Build app
      run: go build -v ./...

    - name: Slack Notification on failure
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: github_builds
        SLACK_USERNAME: "Github CI"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://avatars2.githubusercontent.com/u/25100863?s=40&v=4
        SLACK_TITLE: "CI failed - (Go) FlowerCare"
        SLACK_MESSAGE: "Build failed  :bangbang:"
        SLACK_COLOR: "#ff0000"

  deploy-docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        if: success()
        uses: actions/checkout@v3

      - name: Login to private registery
        if: success()
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTERY_URL }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        if: success()
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker build and push
        if: success()
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_REGISTERY_URL }}/flowercare_collector:v1.0.${{github.run_number}}
          build-args: GO_PRIVATE_REPO_KEY=${{ secrets.REPO_ACCESS }}

      - name: Tag with new ver
        if: success()
        run: |
          git tag v1.0.${{github.run_number}}
          git push origin v1.0.${{github.run_number}}

      - name: Slack Notification on failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: github_builds
          SLACK_USERNAME: "Github CI"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://avatars2.githubusercontent.com/u/25100863?s=40&v=4
          SLACK_TITLE: "CI/CD failed - (Go) FlowerCare Collector"
          SLACK_MESSAGE: "Docker build failed  :bangbang:"
          SLACK_COLOR: "#ff0000"
  
